# Generated by Django 4.1.4 on 2023-02-18 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favourites',
            field=models.ManyToManyField(blank=None, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
